name: Docker Image CI

on: 
  push:
    branches:
    - master

jobs:

  deploy:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    
    - name: Build Docker image
      uses: actions/docker/cli@master
      with:
        args: "build . --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}"

    - name: Authenticate into Google Cloud Platform
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: Configure Docker to use Google Cloud Platform
      uses: actions/gcloud/cli@master
      with:
        args: "auth configure-docker --quiet"

    - name: Push image to GCR
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}"

    - name: Install beta commands and deploy
      uses: actions/gcloud/cli@master
      with:
        args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --region europe-west2 --project ${{ secrets.GCLOUD_PROJECT }} --platform managed"
